### PR TITLE
Upgrade to tools barebone 1.1.2

### PR DESCRIPTION
**Pull request by elsapassaro**
Use `tools-barebone` v1.1.2, which was released to upgrade the parser `ase` to v3.21.1, fixing a bug for parsing cif files.
Moreover, the input file formats in the dropdown menu were reordered.

### CODE REVIEW

**Review by giovannipizzi — APPROVED** [review]
All looks fine, but I didn't check that it works as intended - please (if you didn't to it yet) before merging check that running locally it works fine (./admin-tools/build-docker.sh, ./admin-tools/run-docker.sh) before merging. Thanks!

**Comment by giovannipizzi** [comment]
actually there is one missing thing: upping the version of *this* package, and then once merged, add a git tag on this repository so an image is released on docker hub.

Notes here: https://github.com/materialscloud-org/tools-seekpath/wiki

**Comment by elsapassaro** [comment]
I've built the new image and checked the local container, it seems to work fine - I've checked with the cif file which was not working with the previous `ase` version and a couple of example. Do I need to test something else in particular?

I've now bumped the version of seekpath to v21.05.0. Should I verify that the automatic build works correctly on DockerHub before pushing the tag?

**Review by giovannipizzi — APPROVED** [review]

**Comment by giovannipizzi** [comment]
No, the builds will work if you use the right syntax for the tag.
Just do locally a git pull, add a tag `git tag v21.05.0`, and `git push --tags`.
You should have rights to do it since you are owner of the organisation.

This should trigger an automated build (might take 10-20 mins). Just write me an email if in 1 h it's still not available on docker hub.

**Pull request merged**
